### ISSUE TITLE
The parameters of the model

### ISSUE THREAD

**Issue by ysl-cpp** [yinkalario/EIN-SELD#12]
Hi  yinkalario:
      I counted the parameters of the model ，does  it has about 9 millions?

**Comment by yinkalario** [comment]
Yes, roughly, but you can compress the model or use smaller models. This is not for engineering purpose in the beginning.

**Comment by ysl-cpp** [comment]
Thank you very much, it has been solved . by the way, does the EINV2 model available for the data of 3 mic ?


余绍龙
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "yinkalario/EIN-SELD"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年12月9日(星期五) 晚上8:51
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [yinkalario/EIN-SELD] The parameters of the model (Issue #12)





 
Yes, roughly, but you can compress the model or use smaller models. This is not for engineering purpose in the beginning.
