### ISSUE TITLE
some questions

### ISSUE THREAD

**Issue by yangdongchao** [yinkalario/EIN-SELD#2]
I read your paper(EVENT-INDEPENDENT NETWORK FOR POLYPHONIC SOUND EVENT LOCALIZATION AND DETECTION),and read your code. I find your implementation is different from your paper。
first, you use Transformer Encoder replace GRU. 
second, it seems that you never use EAD Prediction.

**Comment by yinkalario** [comment]
Hi, thanks for your attention to our work.

You may notice that the original Event-Independent Network did not achieve the best score in the challenge. We have improved it. We published another paper _An Improved EIN_, which you can see it in the readme. The code in this repository is based on the newer paper more, but it kept the permutation-invariant training part, and it discloses more on the joint-training of SELD.

Thanks
