### ISSUE TITLE
cPIT Training

### ISSUE THREAD

**Issue by saraalrawi** [yinkalario/EIN-SELD#7]
In your paper, section 3.3, you mentioned and also reported results from cPIT training. 
Unfortunately, I could not find any cPIT config also, in losses.py there is only tPIT function. 

Could you please point out the cPIT training? 

Best, 
Sara

**Comment by catherine-qian** [comment]
did you solve this issue? @saraalrawi

**Comment by yinkalario** [comment]
Hi, sorry the cPIT training is not included in the current version of the code.
