### ISSUE TITLE
environment

### ISSUE THREAD

**Issue by catherine-qian** [yinkalario/EIN-SELD#8]
Thanks for your work!

Could you please let me know which GPU enviornment you are using?
And the batchsize for train/inference?

Thanks!

**Comment by yinkalario** [comment]
The GPU I used is RTX 2080Ti. The environment is based on pytorch and cudnn.

All of the hyper-parameters are listed in ./configs/ein_seld/seld.yaml

Thanks.

**Comment by catherine-qian** [comment]
thanks for your reply.
